# Generated by Django 4.2.11 on 2024-03-12 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0035_auto_20230822_2208"),
        ("NavelOrangeWorm", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="event", name="id",),
        migrations.AddField(
            model_name="event",
            name="cmsplugin_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="cms.cmsplugin",
            ),
            preserve_default=False,
        ),
    ]
