# Generated by Django 4.2.11 on 2024-03-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NavelOrangeWorm", "0003_remove_eventlink_event_eventlink_plugin"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventlink",
            name="linkdesc",
            field=models.CharField(
                default=0, max_length=200, verbose_name="Description"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="eventlink",
            name="link",
            field=models.URLField(max_length=100, verbose_name="URL"),
        ),
    ]
