# Generated by Django 4.2.11 on 2024-03-14 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0035_auto_20230822_2208"),
        ("NavelOrangeWorm", "0004_eventlink_linkdesc_alter_eventlink_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Resource Name"),
                ),
                ("desc", models.CharField(max_length=200, verbose_name="Description")),
            ],
            options={
                "verbose_name": "Resource",
                "verbose_name_plural": "Resources",
                "managed": True,
            },
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="resLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField(max_length=100, verbose_name="URL")),
                (
                    "linkdesc",
                    models.CharField(max_length=200, verbose_name="Description"),
                ),
                (
                    "plugin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="associated_item",
                        to="NavelOrangeWorm.resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Link",
                "verbose_name_plural": "Links",
                "managed": True,
            },
        ),
    ]
